{{- if .Values.appsec.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-appsec-service
  labels:
    app: {{ .Release.Name }}-appsec-service
    {{- with .Values.appsec.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.appsec.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.appsec.service.type }}
  {{- with .Values.appsec.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.appsec.service.loadBalancerClass }}
  loadBalancerClass: {{ . }}
  {{- end }}
  {{- with .Values.appsec.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.appsec.service.type "LoadBalancer") (eq .Values.appsec.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.appsec.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
    - port: 6060
      targetPort: 6060
      protocol: TCP
      name: metrics
    - port: 7422
      targetPort: 7422
      protocol: TCP
      name: appsec
  selector:
    k8s-app: {{ .Release.Name }}
    type: appsec
    version: v1
{{- end }}