{{- if .Values.lapi.enabled }}
{{- if not (eq (include "IsOnlineAPIDisabled" .) "true") }}
{{- if or (eq (include "StoreCAPICredentialsInSecret" .) "true") (eq (include "StoreLAPICscliCredentialsInSecret" .) "true") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }} 
  name: {{ .Release.Name }}-configmap-updater-role
  labels:
    k8s-app: {{ .Release.Name }}
    type: capi-register-job
    version: v1
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-1"
rules:
    - apiGroups: [""]
      resources: ["secrets"]
      resourceNames: ["{{ .Release.Name }}-capi-credentials", "{{ .Release.Name }}-lapi-cscli-credentials"]
      verbs: ["get", "patch"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["create"]
{{- end }}
{{- end }}
--- 
{{- end }}
{{- $hasKubernetes := false -}}
{{- if .Values.agent.additionalAcquisition }}
{{- range .Values.agent.additionalAcquisition }}
{{- if eq .source "kubernetes" }}
{{- $hasKubernetes = true -}}
{{- end }}
{{- end }}
{{- end }}
{{- if $hasKubernetes }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-logs
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
{{- end }}
